version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          command:
            python -m pip install --upgrade pip
            pip install pytest
            pytest TestTriangle.py
      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test